#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "custom_theme.h"
#include "ui_settings_popups.c"
bool custom_theme_color_override(uint32_t a,uint32_t b,uint32_t c,uint32_t *d){(void)a;(void)b;(void)c;(void)d;return false;}
bool custom_theme_metric_override(int32_t a,int32_t b,int32_t c,int32_t *d){(void)a;(void)b;(void)c;(void)d;return false;}
bool custom_theme_accent_override(uint8_t a,uint32_t *b){(void)a;(void)b;return false;}
bool custom_theme_surface_opacity(uint8_t *a){(void)a;return false;}
static void click(lv_obj_t *o){lv_obj_send_event(o,LV_EVENT_CLICKED,NULL);}
static uint16_t raster[1024*600];static int viewport_width=1024;
static void flush(lv_display_t *d,const lv_area_t *a,uint8_t *p){uint16_t *v=(uint16_t*)p;for(int y=a->y1;y<=a->y2;y++)for(int x=a->x1;x<=a->x2;x++)raster[y*viewport_width+x]=*v++;lv_display_flush_ready(d);}
static void snapshot(int theme,const char *name){const char *folder=getenv("THEME_DIALOG_SCREENSHOTS");if(!folder)return;lv_refr_now(NULL);char path[512];snprintf(path,sizeof(path),"%s/%s-theme%d.ppm",folder,name,theme);FILE *f=fopen(path,"wb");assert(f);fprintf(f,"P6\n1024 600\n255\n");for(int i=0;i<1024*600;i++){uint16_t v=raster[i];unsigned char c[3]={(v>>11)*255/31,((v>>5)&63)*255/63,(v&31)*255/31};fwrite(c,1,3,f);}fclose(f);}
static void inside(lv_obj_t *child,lv_obj_t *parent){lv_area_t a,b;lv_obj_get_coords(child,&a);lv_obj_get_coords(parent,&b);if(!(a.x1>=b.x1&&a.x2<=b.x2&&a.y1>=b.y1&&a.y2<=b.y2)){fprintf(stderr,"Outside %d,%d..%d,%d vs %d,%d..%d,%d\n",a.x1,a.y1,a.x2,a.y2,b.x1,b.y1,b.x2,b.y2);abort();}}
static custom_theme_summary_t summaries[CUSTOM_THEME_MAX_COUNT];static size_t count=8;static bool active_custom,fail_select,fail_remove;static ui_theme_id_t active_theme;static char active_id[33];static unsigned selected_calls,removed_calls,changed_calls;static size_t selected_custom,removed_index;
ui_theme_id_t theme_manager_active(void){return active_theme;}
bool theme_manager_custom_active(void){return active_custom;}
const char *custom_theme_active_id(void){return active_id;}
size_t theme_manager_scan_custom_themes(void){return count;}
size_t theme_manager_custom_count(void){return count;}
const custom_theme_summary_t *theme_manager_custom_summary(size_t index){return index<count?&summaries[index]:NULL;}
bool theme_manager_select(ui_theme_id_t theme){selected_calls++;if(fail_select)return false;active_theme=theme;active_custom=false;return true;}
bool theme_manager_select_custom(size_t index){selected_calls++;selected_custom=index;if(fail_select)return false;active_custom=true;snprintf(active_id,sizeof(active_id),"%s",summaries[index].id);return true;}
bool theme_manager_remove_custom(size_t index){removed_calls++;removed_index=index;if(fail_remove)return false;if(active_custom&&!strcmp(active_id,summaries[index].id)){active_custom=false;active_theme=UI_THEME_OPERATOR;}return true;}
static void changed(void){assert(!s_theme_popup&&!s_custom_theme_popup&&!s_custom_remove_popup);changed_calls++;}
static void reset(void){count=8;active_custom=false;fail_select=fail_remove=false;active_theme=UI_THEME_CLASSIC;for(unsigned i=0;i<8;i++){snprintf(summaries[i].id,33,"theme_%u",i);memset(summaries[i].name,'A'+i,40);summaries[i].name[40]=0;memset(summaries[i].author,'a'+i,40);summaries[i].author[40]=0;memset(summaries[i].description,'x',120);summaries[i].description[120]=0;summaries[i].base_theme=i%3;summaries[i].preview_background=0x102030;summaries[i].preview_card=0x304050;summaries[i].preview_text=0xeeeeee;summaries[i].preview_accent=0x33ccff;}}
static void pump(void){lv_tick_inc(20);lv_timer_handler();}
static void layout(lv_obj_t *popup){lv_obj_update_layout(popup);lv_obj_t *body=lv_obj_get_child(popup,1),*footer=lv_obj_get_child(popup,-1);inside(body,popup);inside(footer,popup);for(unsigned i=0;i<lv_obj_get_child_count(footer);i++){lv_obj_t *b=lv_obj_get_child(footer,i);inside(b,footer);inside(lv_obj_get_child(b,0),b);assert(lv_obj_get_height(b)>=48);}lv_area_t a,b;lv_obj_get_coords(footer,&a);lv_obj_scroll_to_y(body,500,LV_ANIM_OFF);lv_obj_update_layout(popup);lv_obj_get_coords(footer,&b);assert(!memcmp(&a,&b,sizeof(a)));lv_obj_scroll_to_y(body,0,LV_ANIM_OFF);}
static lv_obj_t *previews(void){return lv_obj_get_child(lv_obj_get_child(s_theme_popup,1),1);}
static void builtin_layout(void){layout(s_theme_popup);lv_obj_t *grid=previews();assert(lv_obj_get_child_count(grid)==4);for(unsigned i=0;i<4;i++){lv_obj_t *card=lv_obj_get_child(grid,i);inside(card,grid);for(unsigned j=0;j<lv_obj_get_child_count(card);j++)inside(lv_obj_get_child(card,j),card);lv_obj_t *head=lv_obj_get_child(card,0);for(unsigned j=0;j<lv_obj_get_child_count(head);j++)inside(lv_obj_get_child(head,j),head);lv_area_t a;lv_obj_get_coords(card,&a);for(unsigned k=0;k<i;k++){lv_area_t b;lv_obj_get_coords(lv_obj_get_child(grid,k),&b);assert(a.x2<b.x1||b.x2<a.x1||a.y2<b.y1||b.y2<a.y1);}}}
static void custom_layout(void){layout(s_custom_theme_popup);for(unsigned i=0;i<count;i++){lv_obj_t *row=s_custom_rows[i];assert(row);for(unsigned j=0;j<lv_obj_get_child_count(row);j++)inside(lv_obj_get_child(row,j),row);assert(strstr(lv_label_get_text(lv_obj_get_child(row,0)),summaries[i].name));assert(!strcmp(lv_label_get_text(lv_obj_get_child(row,1)),summaries[i].description));}}
int main(void){lv_init();lv_display_t *d=lv_display_create(1024,600);static uint8_t buffer[1024*40*2];lv_display_set_color_format(d,LV_COLOR_FORMAT_RGB565);lv_display_set_buffers(d,buffer,NULL,sizeof(buffer),LV_DISPLAY_RENDER_MODE_PARTIAL);lv_display_set_flush_cb(d,flush);
for(int size=0;size<3;size++)for(int theme=0;theme<4;theme++)for(int density=0;density<3;density++)for(int large=0;large<2;large++){
 viewport_width=(int[]){1024,640,480}[size];lv_display_set_resolution(d,viewport_width,size==2?400:600);ui_theme_set_active(theme);ui_theme_set_density(density);ui_theme_set_accessibility((ui_accessibility_t){.large_text=large});reset();unsigned before=changed_calls,calls=selected_calls;
 ui_settings_popups_show_theme(changed);builtin_layout();if(!size&&density==1&&large)snapshot(theme,"builtins");click(lv_obj_get_child(previews(),0));assert(!s_theme_popup&&changed_calls==before&&selected_calls==calls);
 ui_settings_popups_show_theme(changed);fail_select=true;click(lv_obj_get_child(previews(),1));assert(s_theme_popup&&!s_theme_change_pending);fail_select=false;calls=selected_calls;click(lv_obj_get_child(previews(),1));assert(s_theme_popup&&s_theme_change_pending&&changed_calls==before);click(lv_obj_get_child(previews(),2));assert(selected_calls==calls+1);pump();assert(!s_theme_popup&&!s_theme_change_pending&&changed_calls==before+1);
 ui_settings_popups_show_theme(changed);lv_obj_t *shell=lv_obj_get_child(previews(),3);lv_obj_send_event(shell,LV_EVENT_PRESSED,NULL);click(shell);assert(s_theme_change_pending);pump();assert(active_theme==UI_THEME_OPERATOR_SHELL&&changed_calls==before+2);
 ui_settings_popups_show_theme(changed);custom_theme_manager_show_cb(NULL);custom_layout();if(!size&&density==1&&large)snapshot(theme,"custom");assert(lv_obj_has_state(s_custom_apply_action,LV_STATE_DISABLED));calls=selected_calls;click(s_custom_rows[2]);custom_layout();assert(selected_calls==calls&&!lv_obj_has_state(s_custom_apply_action,LV_STATE_DISABLED));fail_select=true;click(s_custom_apply_action);assert(s_custom_theme_popup&&!s_theme_change_pending);fail_select=false;click(s_custom_apply_action);assert(s_theme_change_pending&&selected_custom==2);pump();assert(!s_theme_popup&&!s_custom_theme_popup&&changed_calls==before+3);
 ui_settings_popups_show_theme(changed);custom_theme_manager_show_cb(NULL);click(s_custom_rows[1]);unsigned removals=removed_calls;click(s_custom_remove_action);assert(s_custom_remove_popup);layout(s_custom_remove_popup);assert(strstr(lv_label_get_text(lv_obj_get_child(lv_obj_get_child(s_custom_remove_popup,1),0)),summaries[1].name));if(!size&&density==1&&large)snapshot(theme,"remove");click(lv_obj_get_child(lv_obj_get_child(s_custom_remove_popup,-1),0));assert(!s_custom_remove_popup&&removed_calls==removals);
 click(s_custom_remove_action);fail_remove=true;click(lv_obj_get_child(lv_obj_get_child(s_custom_remove_popup,-1),1));assert(s_custom_remove_popup);fail_remove=false;click(lv_obj_get_child(lv_obj_get_child(s_custom_remove_popup,-1),1));assert(removed_index==1&&!s_custom_theme_popup&&s_theme_popup&&!s_theme_change_pending);theme_popup_close();
 ui_settings_popups_show_theme(changed);custom_theme_manager_show_cb(NULL);click(s_custom_rows[2]);click(s_custom_remove_action);click(lv_obj_get_child(lv_obj_get_child(s_custom_remove_popup,-1),1));assert(s_theme_change_pending);pump();assert(changed_calls==before+4&&!s_theme_popup);
 ui_settings_popups_show_theme(changed);custom_theme_manager_show_cb(NULL);click(s_custom_rows[1]);click(s_custom_remove_action);strcpy(summaries[1].id,"replaced_id");removals=removed_calls;click(lv_obj_get_child(lv_obj_get_child(s_custom_remove_popup,-1),1));assert(removed_calls==removals);lv_obj_delete(s_theme_popup);assert(!s_custom_remove_popup&&!s_custom_theme_popup&&!s_custom_rows[1]);
 reset();count=0;ui_settings_popups_show_theme(changed);custom_theme_manager_show_cb(NULL);layout(s_custom_theme_popup);assert(lv_obj_has_state(s_custom_apply_action,LV_STATE_DISABLED));click(lv_obj_get_child(lv_obj_get_child(s_custom_theme_popup,-1),0));assert(!s_custom_theme_popup);lv_obj_delete(s_theme_popup);assert(!s_theme_popup&&!s_theme_changed_cb);
}
puts("PASS: all theme/custom dialogs, long names/authors/descriptions, preview bounds and scrolling/pinned actions across themes/densities/text sizes/widths; deferred/deduplicated switching, select/Apply, Keep/Remove, active removal, failed/stale operations, empty list and teardown");return 0;}
